# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

sudo: false

os:
  - linux
julia:
  - 1.0.3
  #- nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: true
before_install:
  #- if [ `uname` = "linux" ]; then sudo apt-get install gmt gmt-dcw gmt-gshhg; fi
      # Get Miniconda from Continuum
      # Need to source the script to set the PATH variable in this environment
      #- source install-miniconda.sh
      #- conda update conda -c conda-forge --yes --quiet
      # Install dependencies
      #- conda install python=3.6 pip -c conda-forge --yes --quiet
      #- conda install --file requirements-dev.txt -c conda-forge --yes --quiet
      # Need the dev channel to get development builds of GMT 6
      #- conda install --file requirements.txt -c conda-forge/label/dev -c conda-forge --yes --quiet
      # Show installed pkg information for postmortem diagnostic
      #- conda list
      # Install GMT trunk
      - pwd
      - sudo apt-get install subversion build-essential cmake libcurl4-gnutls-dev libnetcdf-dev libgdal1-dev libfftw3-dev libpcre3-dev liblapack-dev ghostscript
      #- svn checkout svn://gmtserver.soest.hawaii.edu/gmt5/branches/5.4 $HOME/gmt
      - git clone https://github.com/GenericMappingTools/gmt.git $HOME/gmt
      - PATH="$HOME/gmt/bin:$PATH"
      - export PATH
      - echo 'export PATH="$HOME/gmt/bin:$PATH"' >>~/.bash_profile
      - cd $HOME/gmt
      #- wget ftp://ftp.soest.hawaii.edu/gshhg/gshhg-gmt-2.3.7.tar.gz
      #- wget http://w3.ualg.pt/~jluis/ftp/gshhg-gmt-2.3.7.tar.gz
      - wget https://mirrors.ustc.edu.cn/gmt/gshhg-gmt-2.3.7.tar.gz
      - tar -xvzf gshhg-gmt-2.3.7.tar.gz
      - mkdir build
      - cd build
      - cmake --config Release .. -DSUPPORT_EXEC_IN_BINARY_DIR=TRUE -DGMT_OPENMP=ON -DCMAKE_INSTALL_PREFIX=$HOME/gmt -DGSHHG_ROOT=$HOME/gmt/gshhg-gmt-2.3.7
      - make -j && make install
      - export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$HOME/gmt/lib"
      - cd /home/travis/build/GenericMappingTools/GMT.jl
  #- if [ `uname` = "Darwin" ]; then brew update && brew upgrade && brew install gmt; fi

# uncomment the following lines to override the default test script
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'using Pkg; Pkg.clone(pwd()); Pkg.build("GMT"); Pkg.test("GMT"; coverage=true);'
after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("GMT")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
  - julia -e 'using Pkg; ps=Pkg.PackageSpec(name="Documenter", version="0.19"); Pkg.add(ps); Pkg.pin(ps)'
  - julia -e 'using Pkg; cd(Pkg.dir("GMT")); include(joinpath("docs", "make.jl"))'
