# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
dist: trusty
notifications:
  email: true
before_install:
  - if [ `uname` = "Linux" ]; then
      #sudo apt-get install libgmt-dev;
      # Get Miniconda from Continuum
      # Need to source the script to set the PATH variable in this environment
      # (not the scripts environment)
      - source ci/install-miniconda.sh
      - conda update --yes conda
      # Install dependencies
      - conda install --yes python=$PYTHON pip -c conda-forge
      # Need the dev channel to get development builds of GMT 6
      - conda install --yes --file requirements.txt -c conda-forge/label/dev -c conda-forge
      - conda install --yes --file requirements-dev.txt -c conda-forge
      # Show installed pkg information for postmortem diagnostic
      - conda list
    elif [ `uname` = "Darwin" ]; then
      brew install homebrew/science/gmt;
    fi
# uncomment the following lines to override the default test script
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("GMT"); Pkg.test("GMT"; coverage=true);'
after_success:
  - julia -e 'cd(Pkg.dir("GMT")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("GMT")); include(joinpath("docs", "make.jl"))'