# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

sudo: false

os:
  - linux
dist: eoan
julia:
  - 1.5
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: true
# uncomment the following lines to override the default test script
script:
  #- if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'using Pkg; Pkg.build(); Pkg.test(; coverage=true);'
after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("GMT")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
  - julia -e 'using Pkg; ps=Pkg.PackageSpec(name="Documenter"); Pkg.add(ps); Pkg.pin(ps)'
  - julia -e 'using Pkg; cd(Pkg.dir("GMT")); include(joinpath("docs", "make.jl"))'
