# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

sudo: false

os:
  - osx
julia:
  - 0.6
  - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: true
before_install:
  #- if [ `uname` = "linux" ]; then sudo apt-get install libgmt-dev; fi
      # Get Miniconda from Continuum
      # Need to source the script to set the PATH variable in this environment
      #- source ci/install-miniconda.sh
      #- conda update conda -c conda-forge --yes --quiet
      # Install dependencies
      #- conda install python=3.6 pip -c conda-forge --yes --quiet
      #- conda install --file requirements-dev.txt -c conda-forge --yes --quiet
      # Need the dev channel to get development builds of GMT 6
      #- conda install --file requirements.txt -c conda-forge/label/dev -c conda-forge --yes --quiet
      # Show installed pkg information for postmortem diagnostic
      #- conda list
      # Install GMT trunk
      ##- sudo apt-get install subversion build-essential cmake libcurl4-gnutls-dev libnetcdf-dev libgdal1-dev libfftw3-dev libpcre3-dev liblapack-dev
      ##- svn checkout svn://gmtserver.soest.hawaii.edu/gmt/trunk $HOME/gmt
      ##- PATH="$HOME/gmt/bin:$PATH"
      ##- echo 'export PATH="$HOME/gmt/bin:$PATH"' >>~/.bash_profile
      ##- cd $HOME/gmt
      ##- mkdir build
      ##- cd build
      ##- cmake --config Release .. -DSUPPORT_EXEC_IN_BINARY_DIR=TRUE -DGMT_OPENMP=ON -DCMAKE_INSTALL_PREFIX=$HOME/gmt
      ##- make -j && make install
  - if [ `uname` = "Darwin" ]; then
      brew install gmt;
    fi
# uncomment the following lines to override the default test script
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("GMT"); Pkg.test("GMT"; coverage=true);'
after_success:
  - julia -e 'cd(Pkg.dir("GMT")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("GMT")); include(joinpath("docs", "make.jl"))'
