# From https://github.com/ecmwf/ecmwf-opendata

Dict(
"100u"     => ["100 metre U wind component", "m s-1"],
"100v"     => ["100 metre V wind component", "m s-1"],
"10u"      => ["10 metre U wind component", "m s-1"],
"10v"      => ["10 metre V wind component", "m s-1"],
"10fg"     => ["Maximum 10 metre wind gust since previous post-processing", "m s-1"],
"2d"       => ["2 metre dewpoint temperature", "K"],
"2t"       => ["2 metre temperature", "K"],
"asn"      => ["Snow albedo", ""],
"ewss"     => ["Time-integrated eastward turbulent surface stress", ""],
"lsm"      => ["Land Sea Mask", ""],
"mn2t3"    => ["Minimum temperature at 2 metres in the last 3 hours", "K"],
"mn2t6"    => ["Minimum temperature at 2 metres in the last 6 hours", "K"],
"msl"      => ["Mean sea level pressure", "Pa"],
"mucape"   => ["", ""],
"mx2t3"    => ["Maximum temperature at 2 metres in the last 3 hours", "K"],
"mx2t6"    => ["Maximum temperature at 2 metres in the last 6 hours", "K"],
"nsss"     => ["Time-integrated northward turbulent surface stress", ""],
"ptype"    => ["Precipitation type", ""],
"ro"       => ["Runoff", "m"],
"sdor"     => ["Standard deviation of sub-gridscale orography (step 0)", ""],
"sithick"  => ["Sea ice thickness", "m"],
"skt"      => ["Skin temperature", "K"],
"slor"     => ["Slope of sub-gridscale orography (step 0)", ""],
"sp"       => ["Surface pressure", "Pa"],
"ssr"      => ["Surface net short-wave (solar) radiation", ""],
"ssrd"     => ["Surface net short-wave (solar) radiation downwards", ""],
"st"       => ["Soil Temperature", "K"],
"str"      => ["Surface net long-wave (thermal) radiation", ""],
"stl1"     => ["Soil temperature level 1", "K"],
"strd"     => ["Surface net long-wave (thermal) radiation downwards", ""],
"sve"      => ["", ""],
"svn"      => ["", ""],
"tcw"      => ["", ""],
"tcwv"     => ["Total column vertically-integrated water vapour", "kg m-2"],
"tp"       => ["Total Precipitation", "m"],
"tprate"   => ["Total precipitation rate", ""],
"ttr"      => ["Top net long-wave (thermal) radiation", ""],
"z"        => ["Geopotential (step 0)", ""],
"zos"      => ["Sea surface height", "m"],
"mp2"      => ["Mean zero-crossing wave period", "s"],
"mwd"      => ["Mean wave direction", "Degree"],
"mwp"      => ["Mean wave period", "s"],
"pp1d"     => ["Peak wave period", "s"],
"swh"      => ["Significant height of combined wind waves and swell", "m"]
)

