type _gmt_modules
	backtracker::ASCIIString
	blockmean::ASCIIString
	blockmedian::ASCIIString
	blockmode::ASCIIString
	filter1d::ASCIIString
	fitcircle::ASCIIString
	gmt2kml::ASCIIString
	gmtconnect::ASCIIString
	gmtconvert::ASCIIString
	gmtdefaults::ASCIIString
	gmtget::ASCIIString
	gmtgravmag3d::ASCIIString
	gmtinfo::ASCIIString
	gmtmath::ASCIIString
	gmtselect::ASCIIString
	gmtset::ASCIIString
	gmtsimplify::ASCIIString
	gmtspatial::ASCIIString
	gmtvector::ASCIIString
	gmtwhich::ASCIIString
	gravfft::ASCIIString
	grd2cpt::ASCIIString
	grd2rgb::ASCIIString
	grd2xyz::ASCIIString
	grdblend::ASCIIString
	grdclip::ASCIIString
	grdcontour::ASCIIString
	grdcut::ASCIIString
	grdedit::ASCIIString
	grdfft::ASCIIString
	grdfilter::ASCIIString
	grdgradient::ASCIIString
	grdgravmag3d::ASCIIString
	grdhisteq::ASCIIString
	grdimage::ASCIIString
	grdinfo::ASCIIString
	grdlandmask::ASCIIString
	grdmask::ASCIIString
	grdmath::ASCIIString
	grdpaste::ASCIIString
	grdpmodeler::ASCIIString
	grdproject::ASCIIString
	grdraster::ASCIIString
	grdredpol::ASCIIString
	grdreformat::ASCIIString
	grdrotater::ASCIIString
	grdsample::ASCIIString
	grdseamount::ASCIIString
	grdspotter::ASCIIString
	grdtrack::ASCIIString
	grdtrend::ASCIIString
	grdvector::ASCIIString
	grdview::ASCIIString
	grdvolume::ASCIIString
	greenspline::ASCIIString
	gshhg::ASCIIString
	hotspotter::ASCIIString
	img2grd::ASCIIString
	kml2gmt::ASCIIString
	makecpt::ASCIIString
	mapproject::ASCIIString
	mgd77convert::ASCIIString
	mgd77info::ASCIIString
	mgd77list::ASCIIString
	mgd77magref::ASCIIString
	mgd77manage::ASCIIString
	mgd77path::ASCIIString
	mgd77sniffer::ASCIIString
	mgd77track::ASCIIString
	nearneighbor::ASCIIString
	originator::ASCIIString
	project::ASCIIString
	ps2raster::ASCIIString
	psbasemap::ASCIIString
	psclip::ASCIIString
	pscoast::ASCIIString
	pscontour::ASCIIString
	pscoupe::ASCIIString
	pshistogram::ASCIIString
	psimage::ASCIIString
	pslegend::ASCIIString
	psmask::ASCIIString
	psmeca::ASCIIString
	pspolar::ASCIIString
	psrose::ASCIIString
	psscale::ASCIIString
	pssegy::ASCIIString
	pssegyz::ASCIIString
	pstext::ASCIIString
	psvelo::ASCIIString
	pswiggle::ASCIIString
	psxy::ASCIIString
	psxyz::ASCIIString
	read::ASCIIString
	rotconverter::ASCIIString
	sample1d::ASCIIString
	segy2grd::ASCIIString
	spectrum1d::ASCIIString
	sph2grd::ASCIIString
	sphdistance::ASCIIString
	sphinterpolate::ASCIIString
	sphtriangulate::ASCIIString
	splitxyz::ASCIIString
	surface::ASCIIString
	trend1d::ASCIIString
	trend2d::ASCIIString
	triangulate::ASCIIString
	write::ASCIIString
	x2sys_binlist::ASCIIString
	x2sys_cross::ASCIIString
	x2sys_datalist::ASCIIString
	x2sys_get::ASCIIString
	x2sys_init::ASCIIString
	x2sys_list::ASCIIString
	x2sys_merge::ASCIIString
	x2sys_put::ASCIIString
	x2sys_report::ASCIIString
	x2sys_solve::ASCIIString
	xyz2grd::ASCIIString
end

# Create an instance of empties
n = length(names(_gmt_modules))
gmt_modules = _gmt_modules( ["" for i = 1:n]... )

# Now fill the members

gmt_modules.backtracker="<DI,>DO,EDI,FDI"
gmt_modules.blockmean="<DI,>DO"
gmt_modules.blockmedian="<DI,>DO"
gmt_modules.blockmode="<DI,>DO"
gmt_modules.filter1d="<DI,>DO"
gmt_modules.fitcircle="<DI,>TO"
gmt_modules.gmt2kml="<DI,>TO"
gmt_modules.gmtconnect="<DI,>DO,CDo,LTo,QTo"
gmt_modules.gmtconvert="<DI,>DO"
gmt_modules.gmtdefaults=">TO"
gmt_modules.gmtget=">TO"
gmt_modules.gmtgravmag3d="<DI,FDI,GGO"
gmt_modules.gmtinfo="<DI,>DO"
gmt_modules.gmtmath="<DI,ADI,>DO"
gmt_modules.gmtselect="<DI,CDI,FDI,LDI,>DO"
gmt_modules.gmtset="<TI"
gmt_modules.gmtsimplify="<DI,>DO"
gmt_modules.gmtspatial="<DI,DDI,NDI,TDI,>DO"
gmt_modules.gmtvector="<DI,ADI,>DO"
gmt_modules.gmtwhich="<TI,>TO"
gmt_modules.gravfft="<GI,GGO"
gmt_modules.grd2cpt="<GI,>CO"
gmt_modules.grd2rgb="<GI"
gmt_modules.grd2xyz="<GI,>DO"
gmt_modules.grdblend="<TI,GGO"
gmt_modules.grdclip="<GI,GGO"
gmt_modules.grdcontour="<GI,CCI,-Xo"
gmt_modules.grdcut="<GI,GGO"
gmt_modules.grdedit="<GI,NDI,GGO"
gmt_modules.grdfft="<GI,GGO"
gmt_modules.grdfilter="<GI,GGO"
gmt_modules.grdgradient="<GI,GGO,SGo"
gmt_modules.grdgravmag3d="<GI,FDI,GGO"
gmt_modules.grdhisteq="<GI,GGO,DTo"
gmt_modules.grdimage="<GI,CCI,IGI,-Xo"
#gmt_modules.grdinfo="<GI,>TO"
gmt_modules.grdinfo="<GI"
gmt_modules.grdlandmask="GGO"
gmt_modules.grdmask="<DI,GGO"
gmt_modules.grdmath="<GI,>GO"
gmt_modules.grdpaste="<GI,GGO"
gmt_modules.grdpmodeler="<GI,ETI,FDI,GGO"
gmt_modules.grdproject="<GI,GGO"
gmt_modules.grdraster="GGO,TDo"
gmt_modules.grdredpol="<GI,EGI,GGO"
gmt_modules.grdreformat="<GI,>GO"
gmt_modules.grdrotater="<GI,ETI,FDI,GGO"
gmt_modules.grdsample="<GI,GGO"
gmt_modules.grdseamount="<DI,GGO"
gmt_modules.grdspotter="<GI,AGI,ETI,DGo,LGo,GGO"
gmt_modules.grdtrack="<DI,DDo,GGI,>DO"
gmt_modules.grdtrend="<GI,DGo,TGo,WGo"
gmt_modules.grdvector="<GI,CCI,-Xo"
gmt_modules.grdview="<GI,CCI,GGI,IGI,-Xo"
gmt_modules.grdvolume="<GI,>DO"
gmt_modules.greenspline="<DI,ADI,NDI,TGI,CDo,GGO"
gmt_modules.gshhg=">DO"
gmt_modules.hotspotter="<DI,ETI,GGO"
gmt_modules.img2grd="<GI,GGO"
gmt_modules.kml2gmt="<TI,>DO"
gmt_modules.makecpt=">CO"
gmt_modules.mapproject="<DI,LDI,>DO"
gmt_modules.mgd77convert=""
gmt_modules.mgd77info=">TO"
gmt_modules.mgd77list=">DO"
gmt_modules.mgd77magref="<DI,>DO"
gmt_modules.mgd77manage=""
gmt_modules.mgd77path=">TO"
gmt_modules.mgd77sniffer=""
gmt_modules.mgd77track="-Xo"
gmt_modules.nearneighbor="<DI,GGO"
gmt_modules.originator="<DI,ETI,FDI,>DO"
gmt_modules.project="<DI,>DO"
gmt_modules.ps2raster="--O"
gmt_modules.psbasemap="-XI,-Xo"
gmt_modules.psclip="<DI,-Xo"
gmt_modules.pscoast="-XI,-Xo,>Do"
gmt_modules.pscontour="<DI,CCI,QDI,-Xo"
gmt_modules.pscoupe="<DI,-Xo"
gmt_modules.pshistogram="<DI,-Xo,>Do"
gmt_modules.psimage="<II,-Xo"
gmt_modules.pslegend="<TI,-Xo"
gmt_modules.psmask="<DI,-Xo"
gmt_modules.psmeca="<DI,-Xo"
gmt_modules.pspolar="<DI,-Xo"
gmt_modules.psrose="<DI,-Xo"
gmt_modules.psscale="-XI,CCI,-Xo"
gmt_modules.pssegy="-Xo"
gmt_modules.pssegyz="-Xo"
gmt_modules.pstext="<TI,-Xo"
gmt_modules.psvelo="<DI,-Xo"
gmt_modules.pswiggle="<DI,-Xo"
gmt_modules.psxy="<DI,CCI,-Xo"
gmt_modules.psxyz="<DI,CCI,-Xo"
gmt_modules.read="<?I,>?O"
gmt_modules.rotconverter=">DO"
gmt_modules.sample1d="<DI,NDI,>DO"
gmt_modules.segy2grd="GGO"
gmt_modules.spectrum1d="<DI,>DO"
gmt_modules.sph2grd="<DI,GGO"
gmt_modules.sphdistance="<DI,NDI,QDI,GGO"
gmt_modules.sphinterpolate="<DI,GGO"
gmt_modules.sphtriangulate="<DI,GGO,NDo"
gmt_modules.splitxyz="<DI,>DO"
gmt_modules.surface="<DI,DDI,GGO"
gmt_modules.trend1d="<DI,>DO"
gmt_modules.trend2d="<DI,>DO"
gmt_modules.triangulate="<DI,>DO,GGo"
gmt_modules.write="<?I,>?O"
gmt_modules.x2sys_binlist=">DO"
gmt_modules.x2sys_cross="ATI,>DO"
gmt_modules.x2sys_datalist="LTI,ITI,>DO"
gmt_modules.x2sys_get=">TO"
gmt_modules.x2sys_init=""
gmt_modules.x2sys_list="LTI,ITI,>DO"
gmt_modules.x2sys_merge=""
gmt_modules.x2sys_put=""
gmt_modules.x2sys_report="LTI,ITI,>DO"
gmt_modules.x2sys_solve=""
gmt_modules.xyz2grd="<DI,SDo,GGO"
