function _precompile_()
    ccall(:jl_generating_output, Cint, ()) == 1 || return nothing
    precompile(Tuple{typeof(Base.Printf.ini_dec),Base.GenericIOBuffer{Array{UInt8,1}},Float64,Int64,String,Int64,Int64,Char,Array{UInt8,1}})
    precompile(Tuple{typeof(Base.merge_types),NTuple{4,Symbol},Type{NamedTuple{(:first,),Tuple{Bool}}},Type{NamedTuple{(:F, :D, :par),Tuple{String,String,Tuple{Symbol,Int64}}}}})
    precompile(Tuple{typeof(Base.vect),Float64,Vararg{Any,N} where N})
    precompile(Tuple{typeof(print),Base.GenericIOBuffer{Array{UInt8,1}},Type,String})
    precompile(Tuple{typeof(Base._compute_eltype),Type{Tuple{String,Tuple{String,typeof(GMT.add_opt_fill)},String,Tuple{String,typeof(GMT.add_opt_pen)},String,Tuple{String,typeof(GMT.arg2str)}}}})
    precompile(Tuple{typeof(GMT.add_opt_cpt),Dict{Symbol,Any},String,Array{Symbol,2},Char,Int64,Array{Float64,2}})
    precompile(Tuple{typeof(GMT.finish_PS_module),Dict{Symbol,Any},String,String,Bool,Bool,Bool,Array{Float64,2},Vararg{Any,N} where N})
    precompile(Tuple{typeof(GMT.get_marker_name),Dict{Symbol,Any},Array{Symbol,2},Bool,Bool,Array{Float64,2}})
    precompile(Tuple{typeof(GMT.make_color_column),Dict{Symbol,Any},String,String,Int64,Int64,Int64,Bool,Bool,Array{Float64,2},Nothing})
    precompile(Tuple{typeof(GMT.put_in_legend_bag),Dict{Symbol,Any},String,Array{Float64,2}})
    precompile(Tuple{typeof(GMT.round_wesn),Array{Float64,2}})
    precompile(Tuple{typeof(plot),Array{Float64,1},Array{Float64,1}})
    precompile(Tuple{typeof(print),Base.GenericIOBuffer{Array{UInt8,1}},Ptr{GMT.GMT_MATRIX_v6}})
end
